services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: superSecurePassword!@#$%999
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
